### ISSUE TITLE
Project does not compiling

### ISSUE THREAD

**Issue by kutkovmax** [mattmikolay/rapture#1]
I just wanted to install an interpreter. I cloned the repository, downloaded java, but gradle does not want to work.

<details>
<summary>Error</summary>
<img src="https://github.com/mattmikolay/rapture/assets/99473648/95a17ae0-912d-4198-becb-304851c0b79c"  >
</details>

<details>
<summary>Gradle version</summary>
<img src="https://github.com/mattmikolay/rapture/assets/99473648/d2901079-217a-47da-ac2e-873a3ae72300" width="500" >
</details>

**Comment by mattmikolay** [comment]
Hi @kewtey — thanks for your interest in Rapture.

I’m unable to replicate the error you encountered. [The POM file for that dependency](https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.4.10/kotlin-compiler-embeddable-1.4.10.pom) is in fact available. Can you check your network configuration? Maybe proxy settings, a firewall, or a VPN are interfering here?

**Comment by kutkovmax** [comment]
Hello, I installed JDK 10 and Rapture seems to have installed.

<details>
<summary>Gradle install logs</summary>
<img src="https://github.com/mattmikolay/rapture/assets/99473648/43f2f2b8-2310-492c-adeb-a6838ddb2bdc"  width="500" >
<img src="https://github.com/mattmikolay/rapture/assets/99473648/6eb0b404-b5a3-447e-a995-bb09e73b98aa" width="500" >
</details>



The Rapture works great with English, but does not work at all with Russian

<details>
<img src="https://github.com/mattmikolay/rapture/assets/99473648/23b51022-90bb-4350-b0ed-c12d31c45a1e"  width="500" >
<img src="https://github.com/mattmikolay/rapture/assets/99473648/993dcad7-f936-4960-8a75-3a14ecca2416" width="500" >
</details>

**Comment by mattmikolay** [comment]
> The Rapture works great with English, but does not work at all with Russian

That’s very strange. Is this using the [sample Fibonacci program](https://github.com/mattmikolay/rapture/blob/master/samples/russian/fibonacci.rap) present in this repository? It works locally on my machine:

<img width="896" alt="Screen Shot 2024-02-05 at 8 59 32 PM" src="https://github.com/mattmikolay/rapture/assets/3083108/e1018726-f0c5-46ca-906f-02ca64e05c61">
